name: Tests
on:
  push:
    branches: [dev]

jobs:

  run-tests:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
      - name: Execute Tests
        run: |
          echo "Running Tests ..."
          sleep 10
          echo "Tests PASSED"

  merge-to-main:
    name: Merge dev branch to main
    runs-on: ubuntu-latest
    needs: [run-tests]
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - uses: fregante/setup-git-user@v1
      - name: Merge
        run: |
          git checkout main
          git merge dev --commit -m 'merge dev -> main' 
          git push origin main